# Generated by Django 4.2 on 2023-06-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='almoco',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='entrada',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='saida',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
