# Generated by Django 4.2 on 2023-06-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_status_alter_customuser_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='almoco',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='entrada',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='saida',
            field=models.TimeField(),
        ),
    ]
