# Generated by Django 4.2 on 2023-06-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_almoco_alter_customuser_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='administrador',
            field=models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0),
        ),
    ]
