# Generated by Django 4.2 on 2023-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacoes',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marcacoes',
            name='longitudo',
            field=models.FloatField(default=0),
        ),
    ]
