# Generated by Django 4.2 on 2023-06-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcacoes', '0002_marcacoes_latitude_marcacoes_longitudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marcacoes',
            old_name='longitudo',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='marcacoes',
            name='endereco',
            field=models.CharField(default='DanDan', max_length=200),
            preserve_default=False,
        ),
    ]
