# Generated by Django 4.2 on 2023-08-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcacoes', '0003_rename_longitudo_marcacoes_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacoes',
            name='endereco',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
